# =====================================================================
# Configuración de SonarQube para ms-condominios (Convivo)
# =====================================================================

sonar.projectKey=convivo_ms-condominios
sonar.projectName=Convivo - MS Condominios
sonar.projectVersion=0.1.0

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12

sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/.pytest_cache/**,**/__pycache__/**,**/alembic/**,**/.scannerwork/**

sonar.host.url=http://localhost:9000
