import asyncio
from unittest.mock import AsyncMock, patch

import pytest
from sqlalchemy.dialects import oracle
from sqlalchemy.schema import CreateTable

from app.events import outbox_event
from app.model.condominio import Condominio
from app.model.outbox import Outbox


@pytest.mark.asyncio
async def test_relay_outbox_sigue_reintentando_tras_fallos():
    # Dos caídas seguidas y luego el shutdown: antes, tras 3 fallos la tarea moría para siempre
    publicar = AsyncMock(side_effect=[ConnectionError("rabbit caído"), RuntimeError("bd caída"), asyncio.CancelledError()])
    with (
        patch.object(outbox_event, "_publicar_pendientes", publicar),
        patch.object(outbox_event.asyncio, "sleep", AsyncMock()) as dormir,
        pytest.raises(asyncio.CancelledError),
    ):
        await outbox_event.relay_outbox()

    assert publicar.call_count == 3
    assert dormir.call_count == 2

def test_consulta_pendientes_es_sql_oracle_valido_y_bloquea_filas():
    sql = str(outbox_event.CONSULTA_PENDIENTES.compile(dialect=oracle.dialect()))

    assert "outbox.processed = 0" in sql
    assert "IS 0" not in sql
    assert "FOR UPDATE SKIP LOCKED" in sql

def test_tablas_oracle_usan_identity_sin_indice_duplicado_en_pk():
    for tabla in (Condominio.__table__, Outbox.__table__):
        ddl = str(CreateTable(tabla).compile(dialect=oracle.dialect()))
        assert "GENERATED BY DEFAULT AS IDENTITY" in ddl
        assert not any(indice.columns.keys() == ["id"] for indice in tabla.indexes)
